In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [35]:
# Loading the data
# this is the original dataset
data = pd.read_csv(r'C:\Users\krish\Downloads\risk_factors.csv')

In [36]:
data.head()

Age  Number of sexual partners  First sexual intercourse  \
0   18                        4.0                      15.0   
1   15                        1.0                      14.0   
2   34                        1.0                       NaN   
3   52                        5.0                      16.0   
4   46                        3.0                      21.0   

   Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                 1.0     0.0             0.0                  0.0   
1                 1.0     0.0             0.0                  0.0   
2                 1.0     0.0             0.0                  0.0   
3                 4.0     1.0            37.0                 37.0   
4                 4.0     0.0             0.0                  0.0   

   Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD   ...    \
0                      0.0                              0.0  0.0   ...     
1                      0.0                              0.0  0.0   ...     
2                      0.0                              0.0  0.0   ...     
3                      1.0                              3.0  0.0   ...     
4                      1.0                             15.0  0.0   ...     

   STDs: Time since first diagnosis  STDs: Time since last diagnosis  \
0                               NaN                              NaN   
1                               NaN                              NaN   
2                               NaN                              NaN   
3                               NaN                              NaN   
4                               NaN                              NaN   

   Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  Schiller  Citology  Biopsy  
0          0       0       0   0           0         0         0       0  
1          0       0       0   0           0         0         0       0  
2          0       0       0   0           0         0         0       0  
3          1       0       1   0           0         0         0       0  
4          0       0       0   0           0         0         0       0  

[5 rows x 36 columns]

In [37]:
# look at the target variables
print("Hinselmann : \n",data.Hinselmann.value_counts())
print("Schiller : \n",data.Schiller.value_counts())
print("Biopsy : \n",data.Biopsy.value_counts())

Hinselmann : 
 0    823
1     35
Name: Hinselmann, dtype: int64
Schiller : 
 0    784
1     74
Name: Schiller, dtype: int64
Biopsy : 
 0    803
1     55
Name: Biopsy, dtype: int64


In [38]:
# filter out column data
data = data.drop(['STDs: Time since first diagnosis','STDs: Time since last diagnosis'],axis=1)
data = data.dropna()
data.head()

Age  Number of sexual partners  First sexual intercourse  \
0   18                        4.0                      15.0   
1   15                        1.0                      14.0   
3   52                        5.0                      16.0   
4   46                        3.0                      21.0   
5   42                        3.0                      23.0   

   Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                 1.0     0.0             0.0                  0.0   
1                 1.0     0.0             0.0                  0.0   
3                 4.0     1.0            37.0                 37.0   
4                 4.0     0.0             0.0                  0.0   
5                 2.0     0.0             0.0                  0.0   

   Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD   ...    \
0                      0.0                              0.0  0.0   ...     
1                      0.0                              0.0  0.0   ...     
3                      1.0                              3.0  0.0   ...     
4                      1.0                             15.0  0.0   ...     
5                      0.0                              0.0  0.0   ...     

   STDs:HPV  STDs: Number of diagnosis  Dx:Cancer  Dx:CIN  Dx:HPV  Dx  \
0       0.0                          0          0       0       0   0   
1       0.0                          0          0       0       0   0   
3       0.0                          0          1       0       1   0   
4       0.0                          0          0       0       0   0   
5       0.0                          0          0       0       0   0   

   Hinselmann  Schiller  Citology  Biopsy  
0           0         0         0       0  
1           0         0         0       0  
3           0         0         0       0  
4           0         0         0       0  
5           0         0         0       0  

[5 rows x 34 columns]

In [40]:
print("Hinselmann : \n",data.Hinselmann.value_counts())
print("Schiller : \n",data.Schiller.value_counts())
print("Biopsy : \n",data.Biopsy.value_counts())

Hinselmann : 
 0    638
1     30
Name: Hinselmann, dtype: int64
Schiller : 
 0    605
1     63
Name: Schiller, dtype: int64
Biopsy : 
 0    623
1     45
Name: Biopsy, dtype: int64


In [41]:
# Target features

feats = ["Age","Number of sexual partners","First sexual intercourse","Num of pregnancies",
"Smokes","Smokes (years)","Smokes (packs/year)","Hormonal Contraceptives","Hormonal Contraceptives (years)",
"IUD","IUD (years)","STDs","STDs (number)","STDs:condylomatosis","STDs:cervical condylomatosis","STDs:vaginal condylomatosis",
"STDs:vulvo-perineal condylomatosis","STDs:syphilis","STDs:pelvic inflammatory disease","STDs:genital herpes",
"STDs:molluscum contagiosum","STDs:AIDS","STDs:HIV","STDs:Hepatitis B","STDs:HPV","STDs: Number of diagnosis","Dx:Cancer","Dx:CIN","Dx:HPV","Dx",
"Hinselmann","Citology","Schiller"]

In [42]:
# Split the data
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.3) # Train set by 30%

In [43]:
print("Train : \n", train.Biopsy.value_counts())
print("Test : \n", test.Biopsy.value_counts())


Train : 
 0    434
1     33
Name: Biopsy, dtype: int64
Test : 
 0    189
1     12
Name: Biopsy, dtype: int64


In [44]:
from sklearn.metrics import accuracy_score

In [45]:
# SVM SVC
from sklearn import svm
abc = svm.SVC()
abc.fit(train[feats], train.Biopsy)
pred_svc = abc.predict(test[feats])
acc = accuracy_score(pred_svc, test.Biopsy)                    # accuracy
print("SVC : ",acc)

SVC :  0.940298507463


In [63]:
import warnings; warnings.simplefilter('ignore')
from sklearn.linear_model import SGDClassifier
sgd_l2 = SGDClassifier(penalty='l2', alpha=0.001, loss= 'log').fit(train[feats], train.Biopsy)
sgd_y_pred = sgd_l2.predict(test[feats])
acc = accuracy_score(sgd_y_pred, test.Biopsy)                    # accuracy
print("SGDClassifier : ",acc)

SGDClassifier :  0.940298507463


In [55]:
# SVM LinearSVC

from sklearn.svm import LinearSVC
abc_svc_linear = LinearSVC()
abc_svc_linear.fit(train[feats], train.Biopsy)
pred_linear = abc_svc_linear.predict(test[feats])
acc = accuracy_score(pred_linear, test.Biopsy)                # accuracy
print("SVCLinear : ",acc)

SVCLinear :  0.965174129353


In [70]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(max_depth=6, random_state=1)
RF.fit(train[feats], train.Biopsy)
pred_forest = RF.predict(test[feats])
acc = accuracy_score(pred_forest, test.Biopsy)                 # accuracy
print(acc)

0.950248756219


In [64]:
from sklearn.linear_model import LogisticRegression             
logreg = LogisticRegression()
logreg.fit(train[feats], train.Biopsy)
y_log = logreg.predict(test[feats])
acc = accuracy_score(y_log, test.Biopsy)                        # accuracy
print(acc)                                                      #Logistic regression

0.960199004975


In [54]:
# Cross validation

from sklearn.model_selection import cross_val_score

print("SVC : \n",cross_val_score(abc, data[feats], data.Biopsy, cv=5))
print("Random Forest : \n",cross_val_score(RF, data[feats], data.Biopsy, cv=5))
print("Linear SVC : \n", cross_val_score(abc_svc_linear, data[feats], data.Biopsy, cv=5))

SVC : 
 [ 0.93283582  0.93283582  0.93283582  0.93233083  0.93233083]
Random Forest : 
 [ 0.94029851  0.94029851  0.94029851  0.95488722  0.93984962]
Linear SVC : 
 [ 0.93283582  0.96268657  0.94776119  0.96240602  0.95488722]


In [65]:
# confusion matrix

from sklearn.metrics import confusion_matrix

y_true = test.Biopsy
y_pred = pred_svc
print("SVC : \n",confusion_matrix(y_true, y_pred))

y_true = test.Biopsy
y_pred = pred_forest
print("Random forest : \n",confusion_matrix(y_true, y_pred))

y_true = test.Biopsy
y_pred = pred_linear
print("SVC linear : \n",confusion_matrix(y_true, y_pred))

y_true = test.Biopsy
y_pred = y_log
print("Logistic : \n",confusion_matrix(y_true, y_pred))

SVC : 
 [[189   0]
 [ 12   0]]
Random forest : 
 [[184   5]
 [  5   7]]
SVC linear : 
 [[184   5]
 [  2  10]]
Logistic : 
 [[184   5]
 [  3   9]]


In [59]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_true, pred_svc))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97       189
          1       0.00      0.00      0.00        12

avg / total       0.88      0.94      0.91       201



C:\Users\krish\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [60]:
print(classification_report(y_true, pred_linear))

             precision    recall  f1-score   support

          0       0.99      0.97      0.98       189
          1       0.67      0.83      0.74        12

avg / total       0.97      0.97      0.97       201



In [62]:
print(classification_report(y_true, pred_forest))

             precision    recall  f1-score   support

          0       0.97      0.97      0.97       189
          1       0.58      0.58      0.58        12

avg / total       0.95      0.95      0.95       201



In [66]:
print(classification_report(y_true, y_log))

             precision    recall  f1-score   support

          0       0.98      0.97      0.98       189
          1       0.64      0.75      0.69        12

avg / total       0.96      0.96      0.96       201



In [78]:
temp = ([[51,3,17,6,1,34,3.4,0,0,1,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1]])                   #testing
print(logreg.predict(temp))

[1]


In [79]:
temp = ([[51,3,17,6,1,34,3.4,0,0,1,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1]])
print(RF.predict(temp))

[1]


In [80]:
temp = ([[51,3,17,6,1,34,3.4,0,0,1,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1]])
print(abc_svc_linear.predict(temp))

[1]


In [88]:
temp =([[25,6,17,2,0,0,0,1,2,0,0,1,3,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1]])
print(RF.predict(temp))

[1]


In [89]:
temp =([[25,6,17,2,0,0,0,1,2,0,0,1,3,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1]])
print(logreg.predict(temp))

[1]


In [90]:
temp =([[25,6,17,2,0,0,0,1,2,0,0,1,3,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,1]])
print(abc_svc_linear.predict(temp))

[1]
